[package]
name = "aproxy"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
clap = { version = "4.5", features = ["derive"] }
libaproxy.workspace = true
serde_json.workspace = true

[lints]
workspace = true
