// SPDX-License-Identifier: MIT OR Apache-2.0
//
// Copyright (c) 2025 Sören Langenberg
//
// Author: Sören Langenberg <soeren.langenberg@mailbox.org>

extern crate alloc;
use alloc::vec::Vec;
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug, Clone)]
pub enum ResourceRequestHMAC {
    HmacSha256,
    HmacSha512,
}

/// The attestation request payload sent to the proxy from SVSM.
#[derive(Serialize, Deserialize, Debug)]
pub struct SecretRequest {
    /// The family_id used for identification
    pub family_id: [u8; 16],
    /// The image_id used for identification
    pub image_id: [u8; 16],
    /// The algorithm used for the MAC
    pub algorithm: ResourceRequestHMAC,
    /// The MAC itself over family_id and image_id
    pub mac: Vec<u8>,
}

/// Response from proxy to SVSM indicating the status of attestation as well as an optional secret
/// if successful.
#[derive(Serialize, Deserialize, Debug)]
pub struct SecretResponse {
    /// The nonce needed for AES decryption
    pub nonce: Option<Vec<u8>>,
    /// Remote attestation result
    pub success: bool,
    /// Secret encrypted with the key generated by SVSM
    pub secret: Option<Vec<u8>>,
}
